# Configuration file for Snakemake pipeline

#configurable parameters by user
#run_name for the pipeline
run_name: "Test2"

#put your list of filenames file here, make sure it is one column with no header and just the accession number
sample_list: "/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/0_data/zymo.txt"

#put your file map file here make sure it is two column with no header and just the accession number and absolute path to the file
file_map: "/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/0_data/zymo_filemap.txt"