[workspace]
authors = ["R-Nurdiansyah <rizky.nurdiansyah@hdr.qut.edu.au>"]
channels = ["conda-forge", "bioconda"]
name = "wagtail"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9,<3.12"
polars = ">=0.20.0"
snakemake = ">=9.5.0,<10"
graphviz = ">=12.2.1,<13"
snakemake-executor-plugin-cluster-generic = ">=1.0.9,<2"
