name: CI

on:
  push:
    branches: ["main", "master", "development"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      - name: Run pytest via pixi
        run: pixi run pytest
