name: Test Wagtail accompaniying scripts
on: [push, pull_request]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: test
          environment-file: testing/0_pipeline/envs/mappy.yaml
          python-version: 3.9 # 3.10 fails to setup environment
          # auto-activate-base: false
          # mamba-version: "*" # Appears to be broken as of writing.
          channels: conda-forge,defaults,bioconda
      - run: |
          conda info
          conda list
      #- run: |
      #    pip install -e .
      - name: Run pytest
        run: |
          python -m unittest discover -s testing/0_test -p '*_test.py'
